apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: metric-scrape
spec:
  retentionPeriod: "30"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
  resources:
    requests:
      memory: 500Mi
      cpu: 500m