apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: admin
spec:
  name: admin
  username: admin
  generatePassword: true
  targetRefs:
    # vmsingle
    - crd:
        kind: VMSingle
        name: metric-scrape
        namespace: monitoring
      paths:
        - "/vmui.*"
        - "/prometheus/.*"
    # # vmalert
    # - crd:
    #     kind: VMAlert
    #     name: demo
    #     namespace: vm
    #   paths:
    #     - "/vmalert.*"
    #     - "/api/v1/groups"
    #     - "/api/v1/alert"
    #     - "/api/v1/alerts"