apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-secret-store
    kind: SecretStore
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
  - secretKey: argocdServerAdminPassword
    remoteRef:
      key: argocd
      property: adminPassword
