apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-secret-store
  namespace: argocd
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: openbao-auth
          namespace: openbao
          key: token
